param(
    [Parameter(Mandatory=$false)][string]$ProjectRoot=(Get-Location).Path,
    [Parameter(Mandatory=$false)][ValidateSet('PAPER_CONTROL','SHADOW_ONLY')][string]$ManagerMode='PAPER_CONTROL'
)

$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest

$Branch='rithal-behavior-fix-v1.0.5'
$Raw='https://raw.githubusercontent.com/carvedkarma/NeuralTrade/' + $Branch + '/rithal_behavior_fix_v1_0_5/Install-RithalBehaviorFixV1_0_5_R3_1.ps1'
$Root=[IO.Path]::GetFullPath($ProjectRoot)
$Inner=Join-Path $Root 'Install-RithalBehaviorFixV1_0_5_R3_2_Inner.ps1'
$Downloaded=Join-Path $Root 'Install-RithalBehaviorFixV1_0_5_R3_1_Source.ps1'

Write-Host '[RITHAL_BEHAVIOR_FIX_V1_0_5_R3_2] preparing rank-prewarm hotfix transaction' -ForegroundColor Cyan
Invoke-WebRequest -UseBasicParsing -Uri $Raw -OutFile $Downloaded
$text=[IO.File]::ReadAllText($Downloaded)

$text=$text.Replace('V1_0_5_R3_1','V1_0_5_R3_2')
$text=$text.Replace('v105_r3_1','v105_r3_2')
$text=$text.Replace('V105_R3_1','V105_R3_2')
$text=$text.Replace('R3(?:_1)?_(?:LIVE|MANAGER)_HOOK','R3(?:_[12])?_(?:LIVE|MANAGER)_HOOK')

# R3.2 imports R3.1, which imports R3. Add the R3.1 dependency to the same
# backup/download/compile transaction generated by the R3.1 installer.
$text=$text.Replace(
    "`$R3Dependency=Join-Path `$Neural 'rithal_behavior_fix_v105_r3.py'",
    "`$R3Dependency=Join-Path `$Neural 'rithal_behavior_fix_v105_r3.py'`r`n`$R31Dependency=Join-Path `$Neural 'rithal_behavior_fix_v105_r3_1.py'"
)
$text=$text.Replace(
    '$targets=@($Live,$Manager,$BaseModule,$R3Dependency,$R3Module,',
    '$targets=@($Live,$Manager,$BaseModule,$R3Dependency,$R31Dependency,$R3Module,'
)
$oldDownload='Invoke-WebRequest -UseBasicParsing -Uri "$RawBase/rithal_behavior_fix_v105_r3_2.py" -OutFile $R3Module'
$newDownload='Invoke-WebRequest -UseBasicParsing -Uri "$RawBase/rithal_behavior_fix_v105_r3_1.py" -OutFile $R31Dependency' + "`r`n    " + $oldDownload
$text=$text.Replace($oldDownload,$newDownload)
$text=$text.Replace(
    '& python -m py_compile $BaseModule $R3Dependency $R3Module $Live',
    '& python -m py_compile $BaseModule $R3Dependency $R31Dependency $R3Module $Live'
)

$required=@(
    'RITHAL_BEHAVIOR_FIX_V1_0_5_R3_2',
    'rithal_behavior_fix_v105_r3.py',
    'rithal_behavior_fix_v105_r3_1.py',
    'rithal_behavior_fix_v105_r3_2.py',
    '$R31Dependency',
    'ACTIVE_SHARED_SCORER_PRESERVED',
    '--authority-self-test',
    'Checkpoint directory missing'
)
foreach($token in $required){
    if(-not $text.Contains($token)){
        # The scorer token lives in the Python module rather than the transformed
        # installer source, so verify it directly from GitHub below.
        if($token -ne 'ACTIVE_SHARED_SCORER_PRESERVED'){
            throw "R3.2 installer transformation missing token: $token"
        }
    }
}
[void][scriptblock]::Create($text)
[IO.File]::WriteAllText($Inner,$text,[Text.UTF8Encoding]::new($false))

& powershell -NoProfile -ExecutionPolicy Bypass -File $Inner -ProjectRoot $Root -ManagerMode $ManagerMode
if($LASTEXITCODE -ne 0){throw "RITHAL_BEHAVIOR_FIX_V1_0_5_R3_2 installation failed with exit code $LASTEXITCODE"}
Write-Host '[RITHAL_BEHAVIOR_FIX_V1_0_5_R3_2] canonical installation completed' -ForegroundColor Green
